apiVersion: v1
kind: Service
metadata:
  name: nexo 
  labels:
    app: nexo
spec:
  type: NodePort
  ports:
  - name: http
    port: 5001
    targetPort: http
    protocol: TCP
  selector:
    app: nexo

