name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Start Docker Compose
        run: |
          docker-compose -f hello_world.yml up -d

      - name: Wait for Application to Start
        run: |
          sleep 10

      - name: Test Application
        run: |
          docker logs hello_world

      - name: Stop Docker Compose
        run: |
          docker-compose -f hello_world.yml down
