name: Deploy to Localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t hello_world:latest . 

      - name: Docker Login
        run: |
          docker login

      - name: Tag Docker Image
        run: |
          docker tag hello_world:latest georgiplamenov1/nexo:v1

      - name: Docker Push
        run: |
          docker push georgiplamenov1/nexo:v1

      - name: Start Docker Compose
        run: |
          docker-compose -f hello_world.yml up -d

      - name: Wait for Application to Start
        run: |
          sleep 10

      - name: Test Application
        run: |
          docker logs hello_world

      - name: Stop Docker Compose
        run: |
          docker-compose -f hello_world.yml down
