name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nexo:latest

      - name: Start Docker Compose
        run: |
          docker-compose -f hello_world.yml up -d

      - name: Wait for Application to Start
        run: |
          sleep 10

      - name: Test Application
        run: |
          docker logs hello_world

      - name: Stop Docker Compose
        run: |
          docker-compose -f hello_world.yml down
      - name: Start minikube cluster
        run: |
          minikube start
      
      - name: Run the hello_world and MySQL apps via K8s
        run: |
          kubectl apply -f k8s/
      - name: Delete k8s apps
        run: |
          kubectl delete -f k8s/

      - name: Print a happy/succesful message to the Nexo team
        run: |
          echo "I'm ready with the CI/CD part. I have also wanted to test the application via docker-compose from the pipeline and to apply the k8s manifests from it as well. Otherwise I'm aware of it should be finished , after the build and push docker image step is completed :)"